INSERT INTO students (name, age, major) VALUES ('Alice', 20, 'Computer Science');
INSERT INTO students (name, age, major) VALUES ('Bob', 22, 'Mathematics');
INSERT INTO students (name, age, major) VALUES ('Charlie', 21, 'Physics');
INSERT INTO students (name, age, major) VALUES ('David', 23, 'Chemistry');
INSERT INTO students (name, age, major) VALUES ('Eve', 20, 'Biology');
INSERT INTO students (name, age, major) VALUES ('Frank', 22, 'History');
INSERT INTO students (name, age, major) VALUES ('Grace', 21, 'English Literature');
INSERT INTO students (name, age, major) VALUES ('Hannah', 23, 'Art History');
INSERT INTO students (name, age, major) VALUES ('Isaac', 20, 'Economics');
INSERT INTO students (name, age, major) VALUES ('Jack', 24, 'Philosophy');